version: '2'
services:

  dev:
    container_name: mconf_web_dev
    build: .
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - dev_db
      - dev_redis
    environment:
      - MCONF_REDIS_HOST=dev_redis
      - MCONF_REDIS_PASSWORD=BCsy8zMwZay669ii
      - MCONF_DATABASE_DEV_HOST=dev_db
      - MCONF_DATABASE_DEV_NAME=mconf_web_dev
      - MCONF_DATABASE_DEV_USERNAME=mconfweb
      - MCONF_DATABASE_DEV_PASSWORD=mconfweb
      - RAILS_ENV=development
    volumes:
      - ./:/usr/src/app
    command: bash -c "rake db:create db:migrate && rails s -p3000"
  dev_db:
    container_name: mconf_web_dev_db
    image: mysql:5.6
    expose:
      - "3306"
    volumes:
      - ~/.docker-volumes/mconf-web/dev/mysql/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mconfweb
      - MYSQL_DATABASE=mconf_web_dev
      - MYSQL_USER=mconfweb
      - MYSQL_PASSWORD=mconfweb
  dev_redis:
    container_name: mconf_web_dev_redis
    image: redis:3.2
    expose:
      - "6379"
    command: redis-server --requirepass "BCsy8zMwZay669ii"

  test:
    container_name: mconf_web_test
    build: .
    tty: true
    depends_on:
      - test_db
      - test_redis
    environment:
      - MCONF_REDIS_HOST=test_redis
      - MCONF_REDIS_PASSWORD=BHAy8zMwZay669ii
      - MCONF_DATABASE_TEST_HOST=test_db
      - MCONF_DATABASE_TEST_NAME=mconf_web_test
      - MCONF_DATABASE_TEST_USERNAME=mconfweb
      - MCONF_DATABASE_TEST_PASSWORD=mconfweb
      - RAILS_ENV=test
    volumes:
      - ./:/usr/src/app
    command: bash -c "rake"
  test_db:
    container_name: mconf_web_test_db
    image: mysql:5.6
    expose:
      - "3306"
    volumes:
      - ~/.docker-volumes/mconf-web/test/mysql/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mconfweb
      - MYSQL_DATABASE=mconf_web_test
      - MYSQL_USER=mconfweb
      - MYSQL_PASSWORD=mconfweb
  test_redis:
    container_name: mconf_web_test_redis
    image: redis:3.2
    expose:
      - "6379"
    command: redis-server --requirepass "BHAy8zMwZay669ii"
